### PR TITLE
fixes for krew index

### PR DESCRIPTION
**Pull request by Slach**
fixes after https://github.com/kubernetes-sigs/krew-index/pull/3557
how to test krew-index manually?

### CODE REVIEW

**Comment by Slach** [comment]
tested manually with 
```bash
docker run --rm -v ./.krew/tail.yaml:/tmp/template-file.yaml ghcr.io/rajatjindal/krew-release-bot:v0.0.46 krew-release-bot template --tag 0.17.2 --template-file /tmp/template-file.yaml 1>/tmp/tail.yaml

go install sigs.k8s.io/krew/cmd/validate-krew-manifest@latest

~/go/bin/validate-krew-manifest -manifest /tmp/tail.yaml  
```

**Comment by Slach** [comment]
```
I1227 12:46:06.785272   16076 main.go:68] reading file "tail.yaml"                                                                                                                                                  I1227 12:46:06.812776   16076 main.go:85] structural validation OK                                                                                                                                                  I1227 12:46:06.812776   16076 main.go:93] all spec.platform[] items are used                                                                                                                                        I1227 12:46:06.813776   16076 main.go:99] no overlapping spec.platform[].selector                                                                                                                                   I1227 12:46:06.823773   16076 main.go:104] installing spec.platform[0]                                                                                                                                              I1227 12:46:51.870289   16076 main.go:108] installed  spec.platforms[0]                                                                                                                                             I1227 12:46:51.870289   16076 main.go:104] installing spec.platform[1]                                                                                                                                              I1227 12:47:49.241802   16076 main.go:108] installed  spec.platforms[1]                                                                                                                                             I1227 12:47:49.244240   16076 main.go:104] installing spec.platform[2]                                                                                                                                              I1227 12:48:07.778364   16076 main.go:108] installed  spec.platforms[2]                                                                                                                                             I1227 12:48:07.778364   16076 main.go:104] installing spec.platform[3]                                                                                                                                              I1227 12:48:32.151093   16076 main.go:108] installed  spec.platforms[3]                                                                                                                                             I1227 12:48:32.151093   16076 main.go:104] installing spec.platform[4]                                                                                                                                              I1227 12:49:30.511562   16076 main.go:108] installed  spec.platforms[4]                                                                                                                                             I1227 12:49:30.511562   16076 main.go:104] installing spec.platform[5]                                                                                                                                              I1227 12:50:28.876685   16076 main.go:108] installed  spec.platforms[5]                                                                                                                                             2023/12/27 12:50:28 all 6 spec.platforms installed fine  
```

please merge it, release 0.17.3  and create PR in krew-index

**Comment by Slach** [comment]
@mnaser please look, merge and tag new release

**Comment by mnaser** [comment]
thank you @Slach

**Pull request merged**
