### PR TITLE
Handle the case when listing namespaces is forbidden

### LINKED ISSUE #12: error when used with restricted access rights
When I try to use kail to get logs from an svc I get this error:
```
./kail --ns=ns1 --context=dev  --svc=projector
kail: error: Can't connnect to kubernetes: namespaces is forbidden: User "..." cannot list namespaces at the cluster scope
```

It seems like kail tries to list namespaces despite being given a precise namespace and svc.

Am I missing something?

### PR DESCRIPTION
**Pull request by carlossg**
Ignore a forbidden error as that means we can connect to the api server
Do not try to watch at cluster level when we only need one namespace

Fixes #12

### CODE REVIEW

**Comment by boz** [comment]
Looks great @carlossg, thank you.  I'll play around with it shortly.

**Comment by carlossg** [comment]
maybe we just need to check if the namespace exists, and if so, watch only that one.
That would keep the existing behavior intact

**Comment by carlossg** [comment]
this should work out that case

**Comment by angelbarrera92** [comment]
Is this feature ready to be merged?

**Comment by carlossg** [comment]
I've been using it for weeks, just waiting for @boz to approve

**Comment by boz** [comment]
Thank you so much.  Sorry for the delay.

**Pull request merged**
